### ISSUE TITLE
interactive=0 auto commits with `init Craft`

### ISSUE THREAD

**Issue by Maybach91** [fortrabbit/craft-copy#158]
**Case:**
Uncomitted changes in the project and running `code/up` with the following config:

config.yaml
```yaml

before:
    # Before deploying code by Git, please:
    code/up:
        # 1. Run your NPM production build
        - "cd buildchain && npm run build"
        # 2. Sync the results of the build up
        - "php craft copy/folder/up production web/dist -i=0"
```

This (`-i=0`) leads to a commit made by craft-copy which says `init Craft`. Doing this multiple times is confusing for the commit history. 

Maybe a config setting to overwrite the [default commit message](https://github.com/fortrabbit/craft-copy/blob/476773aa91ba7cb1440833c84e510daad4112d7a/src/Actions/CodeUpAction.php#L95) or something like more according to the action which triggered, like `chore: code/up` or more explaining. But `init Craft` is confusing in this case.
